# Generated by Django 4.2.7 on 2024-04-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multipleUserApp', '0002_delete_lastgeneratedid_studentprofile_first_name_and_more'),
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to='multipleUserApp.teacher'),
        ),
    ]
