# Generated by Django 4.2.7 on 2024-04-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_department_rename_name_class_class_name_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Department',
        ),
        migrations.AddField(
            model_name='subject',
            name='departments',
            field=models.ManyToManyField(blank=True, to='administrators.department'),
        ),
    ]
