# Generated by Django 4.2.7 on 2024-04-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multipleUserApp', '0002_delete_lastgeneratedid_studentprofile_first_name_and_more'),
        ('administrators', '0004_remove_subject_department_subject_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipleUserApp.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject', 'class_assigned')},
            },
        ),
    ]
